/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package T1MulticastApp;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.*;

public class App {

    public static void main(String[] args){
        try {
            InetAddress address = getAddressByString(args[0]);
            String name = getName(args[1]);
            Model.IP_TYPE ipType = isIpv4(args[0]) ? Model.IP_TYPE.IPV4 : Model.IP_TYPE.IPV6;
            Controller controller = new Controller();
            controller.startApp(name, address, ipType);
        } catch (Exception e){
            System.err.println("Incorrect passed args.\nError: " + e.getLocalizedMessage() + "\nPass args [IP] [NAME] with command-line");
            System.exit(1);
        }
    }

    private static InetAddress getAddressByString(String ipMaybe) throws UnknownHostException {
        if(isIpv4(ipMaybe))
        {
            String[] ipParts = ipMaybe.split("\\.");
            byte[] ip = new byte[4];
            for(int i = 0, maxParts = 4; i < maxParts; i++ ){
                ip[i] =((byte)Integer.parseInt(ipParts[i]));
            }
            return InetAddress.getByAddress(ip);
        } else if(isIpv6(ipMaybe))
        {
            String[] ipParts = ipMaybe.split(":");
            String hexIpString = String.join("",ipParts);
            HexFormat hex = HexFormat.of().withLowerCase();
            byte[] ipv6InBytes = hex.parseHex(hexIpString);
            return InetAddress.getByAddress(ipv6InBytes);
        } else
        {
            throw new RuntimeException("Incorrect passed ip.\n");
        }
    }

    private static String getName(String arg){
        if(arg.length() == 0 || arg.length() > Model.APP_USER_MAX_NAME){
            throw new RuntimeException("Invalid name.");
        }
        return arg;
    }

    private static boolean isIpv4(String ipMaybe){
        return ipMaybe.indexOf('.') != -1;
    }

    private static boolean isIpv6(String ipMaybe){
        return ipMaybe.indexOf(':') != -1;
    }
}
